CREATE TABLE tb_missoes (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome_da_missao VARCHAR(255),
                            email VARCHAR(255) UNIQUE,
                            dificuldade VARCHAR(255)
);

CREATE TABLE tb_cadastro (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome VARCHAR(255),
                             email VARCHAR(255) UNIQUE,
                             idade INT,
                             ing_url VARCHAR(255),
                             missoes_id BIGINT,
                             CONSTRAINT fk_missao
                                 FOREIGN KEY (missoes_id)
                                     REFERENCES tb_missoes(id)
);